force_charge:
  fields:
    entry_id:
      required: false
      example: "abc123"
      selector:
        config_entry:
          integration: alphaess_modbus
    power_kw:
      required: false
      default: 5
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kW
    duration_min:
      required: false
      default: 120
      selector:
        number:
          min: 0
          max: 480
          step: 5
          unit_of_measurement: min
    cutoff_soc:
      required: false
      default: 100
      selector:
        number:
          min: 4
          max: 100
          step: 1
          unit_of_measurement: "%"

force_discharge:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus
    power_kw:
      required: false
      default: 5
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kW
    duration_min:
      required: false
      default: 120
      selector:
        number:
          min: 0
          max: 480
          step: 5
          unit_of_measurement: min
    cutoff_soc:
      required: false
      default: 10
      selector:
        number:
          min: 4
          max: 100
          step: 1
          unit_of_measurement: "%"

force_export:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus
    power_kw:
      required: false
      default: 5
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kW
    duration_min:
      required: false
      default: 120
      selector:
        number:
          min: 0
          max: 480
          step: 5
          unit_of_measurement: min
    cutoff_soc:
      required: false
      default: 10
      selector:
        number:
          min: 4
          max: 100
          step: 1
          unit_of_measurement: "%"

dispatch:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus
    mode:
      required: false
      default: 2
      selector:
        number:
          min: 1
          max: 19
          step: 1
    power_kw:
      required: false
      default: 0
      selector:
        number:
          min: -20
          max: 20
          step: 0.1
          unit_of_measurement: kW
    duration_min:
      required: false
      default: 120
      selector:
        number:
          min: 0
          max: 480
          step: 5
          unit_of_measurement: min
    cutoff_soc:
      required: false
      default: 100
      selector:
        number:
          min: 4
          max: 100
          step: 1
          unit_of_measurement: "%"

dispatch_reset:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus

sync_datetime:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus

set_charging_periods:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus
    period_1_start:
      required: true
      selector:
        time:
    period_1_stop:
      required: true
      selector:
        time:
    period_2_start:
      required: true
      selector:
        time:
    period_2_stop:
      required: true
      selector:
        time:

set_discharging_periods:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: alphaess_modbus
    period_1_start:
      required: true
      selector:
        time:
    period_1_stop:
      required: true
      selector:
        time:
    period_2_start:
      required: true
      selector:
        time:
    period_2_stop:
      required: true
      selector:
        time:
